-- Project
DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug varchar NOT NULL,
    name varchar NOT NULL,
    attributions jsonb, -- text[]
    icon_font_css_url varchar NOT NULL,
    polygon geometry(Polygon, 4326) NOT NULL,
    bbox_line geometry(Linestring, 4326) NOT NULL GENERATED ALWAYS AS (
        ST_MakeLine(
            ST_MakePoint(ST_XMin(polygon), ST_YMin(polygon)),
            ST_MakePoint(ST_XMax(polygon), ST_YMax(polygon))
        )
    ) STORED
);

-- Theme
DROP TABLE IF EXISTS themes CASCADE;
CREATE TABLE themes(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id int NOT NULL,
    slug varchar NOT NULL,
    name jsonb NOT NULL, -- Tanslation Object.
    description jsonb, -- Tanslation Object.
    site_url varchar NOT NULL,
    main_url varchar NOT NULL,
    logo_url varchar NOT NULL,
    favicon_url varchar NOT NULL,
    CONSTRAINT menu_items_fk_project_id FOREIGN KEY(project_id) REFERENCES projects(id)
);

-- Sources

DROP TABLE IF EXISTS sources_osm CASCADE;
CREATE TABLE sources_osm(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug varchar NOT NULL,
    label jsonb, -- Tanslation Object
    label_popup jsonb, -- Tanslation Object
    label_details jsonb, -- Tanslation Object
    -- Popup
    popup_properties jsonb, -- text[]. List of tags to be displyed
    -- Details
    details_enable boolean,
    -- OSM
    overpass_query text NOT NULL, -- Overpass API part of the query filter
    map_contrib_theme_url text, -- URL to a map contrib theme
    extra_tags jsonb -- text[]
);

DROP TABLE IF EXISTS sources_tourinsoft CASCADE;
CREATE TABLE sources_tourinsoft(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug varchar NOT NULL,
    label jsonb, -- Tanslation Object
    label_popup jsonb, -- Tanslation Object
    label_details jsonb, -- Tanslation Object
    -- Popup
    popup_properties jsonb, -- text[]. List of tags to be displyed
    -- Details
    details_enable boolean,
    -- Tourinsoft
    url varchar NOT NULL,
    photos_base_url varchar NOT NULL
);

DROP TABLE IF EXISTS sources_cms CASCADE;
CREATE TABLE sources_cms(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug varchar NOT NULL,
    label jsonb, -- Tanslation Object
    label_popup jsonb, -- Tanslation Object
    label_details jsonb, -- Tanslation Object
    -- Popup
    popup_properties jsonb, -- text[]. List of tags to be displyed
    -- Details
    details_enable boolean,
    -- CMS
    extra_tags jsonb -- text[]
);


-- Property labels
DROP TABLE IF EXISTS property_labels;
CREATE TABLE property_labels(
    property varchar PRIMARY KEY,
    property_label jsonb, -- Tanslation Object
    property_label_details jsonb, -- Tanslation Object
    property_label_popup jsonb, -- Tanslation Object
    property_label_filter jsonb, -- Tanslation Object
    value_labels jsonb, -- Values and Tanslation Object
    value_labels_list jsonb, -- Values and Tanslation Object
    value_labels_popup jsonb -- Values and Tanslation Object
);


-- Category

DROP TYPE IF EXISTS menu_item_display_mode_type CASCADE;
CREATE TYPE menu_item_display_mode_type AS ENUM ('compact', 'large');
DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE categories(
    -- Category
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug varchar NOT NULL,
    name jsonb NOT NULL, -- Tanslation Object. Category name
    search_indexed boolean DEFAULT true NOT NULL, -- This menu content is indexed by the search engine, or not.
    -- UI
    icon varchar NOT NULL, -- CSS icon
    color varchar NOT NULL, -- CSS color
    tourism_style_class jsonb, -- text[]. One up to three lenght array of class from data ontology.
    tourism_style_merge boolean, -- Is this category used in the vector tiles background map.
    display_mode menu_item_display_mode_type DEFAULT 'compact'::menu_item_display_mode_type NOT NULL,
    zoom smallint -- Zoom level to show this category POI.
);

DROP TYPE IF EXISTS category_filters_type_type CASCADE;
CREATE TYPE category_filters_type_type AS ENUM ('multiselection', 'checkboxes_list', 'boolean');
DROP TABLE IF EXISTS category_filters CASCADE;
CREATE TABLE category_filters(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id int NOT NULL,
    type category_filters_type_type NOT NULL, -- filter type
    property varchar NOT NULL, -- The POI property to filter on
    values jsonb, -- text[], Values of the property available for filter.
    CONSTRAINT category_filters_fk_category_id FOREIGN KEY(category_id) REFERENCES categories(id)
);

DROP TABLE IF EXISTS categorie_sources_osm CASCADE;
CREATE TABLE categorie_sources_osm(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id int,
    source_osm_id int,
    UNIQUE(category_id, source_osm_id),
    CONSTRAINT categorie_sources_osm_fk_category_id FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT categorie_sources_osm_fk_sources_osm_id FOREIGN KEY(source_osm_id) REFERENCES sources_osm(id)
);

DROP TABLE IF EXISTS categorie_sources_tourinsoft CASCADE;
CREATE TABLE categorie_sources_tourinsoft(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id int,
    source_tourinsoft_id int,
    UNIQUE(category_id, source_tourinsoft_id),
    CONSTRAINT categorie_sources_tourinsoft_fk_category_id FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT categorie_sources_tourinsoft_fk_sources_tourinsoft_id FOREIGN KEY(source_tourinsoft_id) REFERENCES sources_tourinsoft(id)
);

DROP TABLE IF EXISTS categorie_sources_cms CASCADE;
CREATE TABLE categorie_sources_cms(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id int,
    source_cms_id int,
    UNIQUE(category_id, source_cms_id),
    CONSTRAINT categorie_sources_cms_fk_category_id FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT categorie_sources_cms_fk_sources_cms_id FOREIGN KEY(source_cms_id) REFERENCES sources_cms(id)
);


-- Menu

-- Menu group
DROP TABLE IF EXISTS menu_groups CASCADE;
CREATE TABLE menu_groups(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug varchar NOT NULL,
    name jsonb NOT NULL, -- Translation Object
    -- UI
    icon varchar NOT NULL, -- CSS icon
    color varchar NOT NULL, -- CSS color
    tourism_style_class jsonb, -- text[]. One up to three lenght array of class from data ontology.
    display_mode menu_item_display_mode_type DEFAULT 'compact'::menu_item_display_mode_type NOT NULL
);

-- Menu item
DROP TABLE IF EXISTS menu_items CASCADE;
CREATE TABLE menu_items(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    theme_id int NOT NULL,
    -- Menu
    parent_id int, -- This menu item a sub menu item this parent menu item. NULL for main menu items.
    index_order smallint NOT NULL, -- Item index order on menu show.
    hidden boolean DEFAULT false NOT NULL, -- This menu item is hidden on menu, or not.
    selected_by_default boolean DEFAULT false NOT NULL, -- This menu item is selected by default on display, or not.
    -- Content
    category_id int,
    menu_group_id int,
    CONSTRAINT menu_items_fk_theme_id FOREIGN KEY(theme_id) REFERENCES themes(id),
    CONSTRAINT menu_items_fk_parent_id FOREIGN KEY(parent_id) REFERENCES menu_items(id),
    CONSTRAINT menu_items_fk_category_id FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT menu_items_fk_menu_group_id FOREIGN KEY(menu_group_id) REFERENCES menu_groups(id)
);


-- POIs

-- DROP TABLE IF EXISTS poi_tourinsoft CASCADE;
-- CREATE TABLE poi_tourinsoft(
--     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     slug varchar,
--     project_id int,
--     source_tourinsoft_id int,
--     geom geometry(Point, 4326),
--     properties jsonb,
--     CONSTRAINT menu_items_fk_project_id FOREIGN KEY(project_id) REFERENCES projects(id),
--     CONSTRAINT menu_items_fk_source_tourinsoft_id FOREIGN KEY(source_tourinsoft_id) REFERENCES sources_tourinsoft(id)
-- );
